version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null

      - name: view_count
        tests:
          - not_null

      - name: forward_count
        tests:
          - not_null

  - name: dim_channels
    columns:
      - name: channel_key
        tests:
          - unique
          - not_null

      - name: channel_name
        tests:
          - not_null

  - name: dim_dates
    columns:
      - name: full_date
        tests:
          - unique
          - not_null
